# Basic configuration
title: AI On It
description: AI On It Privacy Policy
theme: jekyll-theme-cayman

# Markdown processing settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Optional settings
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
